### ISSUE TITLE
Call either gtmOnSuccess or gtmOnFailure exactly once every time your template is run.

### ISSUE THREAD

**Issue by phamdannyh** [Borlabs-Ben/Borlabs-Cookie-GTM-Variable-Template#1]
When reviewing your template we've noticed that gtmOnSuccess or gtmOnFailure are called incorrectly. This is required so that users can sequence their tags correctly.

https://github.com/Borlabs/Borlabs-Cookie-GTM-Variable-Template/blob/f5d9adeee7b5d46bbb19c8e51b9980773ac2c936/template.tpl#L40

**Comment by constantingraf** [comment]
Thanks for creating an issue! Are you one of the reviewers at Google? Is calling `gtmOnSuccess` or `gtmOnFailure` really required for a variable template? I just looked into many of the variable templates in the GTM gallery and none of them call this function.

**Comment by philpott** [comment]
Sorry for the delay. You are correct Variables do not need to include on success.

**Comment by constantingraf** [comment]
@philpott Thanks for the information! But I still don't understand the setting of this issue. Is @phamdannyh another account of yours? And if not: are you both reviewers at Google?

**Comment by philpott** [comment]
Not another account of mine, but yes we are reviewers at Google. FYI this template has been approved and should appear shortly.

**Comment by constantingraf** [comment]
Perfect, thanks! :)
